# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/andrea/lab2/MyCalo

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/andrea/lab2/MyCalo/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/andrea/lab2/MyCalo/src/CMakeFiles /home/andrea/lab2/MyCalo/src/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/andrea/lab2/MyCalo/src/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MyCalo

# Build rule for target.
MyCalo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MyCalo
.PHONY : MyCalo

# fast build rule for target.
MyCalo/fast:
	$(MAKE) -f CMakeFiles/MyCalo.dir/build.make CMakeFiles/MyCalo.dir/build
.PHONY : MyCalo/fast

MyCalo.o: MyCalo.cc.o

.PHONY : MyCalo.o

# target to build an object file
MyCalo.cc.o:
	$(MAKE) -f CMakeFiles/MyCalo.dir/build.make CMakeFiles/MyCalo.dir/MyCalo.cc.o
.PHONY : MyCalo.cc.o

MyCalo.i: MyCalo.cc.i

.PHONY : MyCalo.i

# target to preprocess a source file
MyCalo.cc.i:
	$(MAKE) -f CMakeFiles/MyCalo.dir/build.make CMakeFiles/MyCalo.dir/MyCalo.cc.i
.PHONY : MyCalo.cc.i

MyCalo.s: MyCalo.cc.s

.PHONY : MyCalo.s

# target to generate assembly for a file
MyCalo.cc.s:
	$(MAKE) -f CMakeFiles/MyCalo.dir/build.make CMakeFiles/MyCalo.dir/MyCalo.cc.s
.PHONY : MyCalo.cc.s

MyCaloActionInitialization.o: MyCaloActionInitialization.cc.o

.PHONY : MyCaloActionInitialization.o

# target to build an object file
MyCaloActionInitialization.cc.o:
	$(MAKE) -f CMakeFiles/MyCalo.dir/build.make CMakeFiles/MyCalo.dir/MyCaloActionInitialization.cc.o
.PHONY : MyCaloActionInitialization.cc.o

MyCaloActionInitialization.i: MyCaloActionInitialization.cc.i

.PHONY : MyCaloActionInitialization.i

# target to preprocess a source file
MyCaloActionInitialization.cc.i:
	$(MAKE) -f CMakeFiles/MyCalo.dir/build.make CMakeFiles/MyCalo.dir/MyCaloActionInitialization.cc.i
.PHONY : MyCaloActionInitialization.cc.i

MyCaloActionInitialization.s: MyCaloActionInitialization.cc.s

.PHONY : MyCaloActionInitialization.s

# target to generate assembly for a file
MyCaloActionInitialization.cc.s:
	$(MAKE) -f CMakeFiles/MyCalo.dir/build.make CMakeFiles/MyCalo.dir/MyCaloActionInitialization.cc.s
.PHONY : MyCaloActionInitialization.cc.s

MyCaloDetectorConstruction.o: MyCaloDetectorConstruction.cc.o

.PHONY : MyCaloDetectorConstruction.o

# target to build an object file
MyCaloDetectorConstruction.cc.o:
	$(MAKE) -f CMakeFiles/MyCalo.dir/build.make CMakeFiles/MyCalo.dir/MyCaloDetectorConstruction.cc.o
.PHONY : MyCaloDetectorConstruction.cc.o

MyCaloDetectorConstruction.i: MyCaloDetectorConstruction.cc.i

.PHONY : MyCaloDetectorConstruction.i

# target to preprocess a source file
MyCaloDetectorConstruction.cc.i:
	$(MAKE) -f CMakeFiles/MyCalo.dir/build.make CMakeFiles/MyCalo.dir/MyCaloDetectorConstruction.cc.i
.PHONY : MyCaloDetectorConstruction.cc.i

MyCaloDetectorConstruction.s: MyCaloDetectorConstruction.cc.s

.PHONY : MyCaloDetectorConstruction.s

# target to generate assembly for a file
MyCaloDetectorConstruction.cc.s:
	$(MAKE) -f CMakeFiles/MyCalo.dir/build.make CMakeFiles/MyCalo.dir/MyCaloDetectorConstruction.cc.s
.PHONY : MyCaloDetectorConstruction.cc.s

MyCaloEventAction.o: MyCaloEventAction.cc.o

.PHONY : MyCaloEventAction.o

# target to build an object file
MyCaloEventAction.cc.o:
	$(MAKE) -f CMakeFiles/MyCalo.dir/build.make CMakeFiles/MyCalo.dir/MyCaloEventAction.cc.o
.PHONY : MyCaloEventAction.cc.o

MyCaloEventAction.i: MyCaloEventAction.cc.i

.PHONY : MyCaloEventAction.i

# target to preprocess a source file
MyCaloEventAction.cc.i:
	$(MAKE) -f CMakeFiles/MyCalo.dir/build.make CMakeFiles/MyCalo.dir/MyCaloEventAction.cc.i
.PHONY : MyCaloEventAction.cc.i

MyCaloEventAction.s: MyCaloEventAction.cc.s

.PHONY : MyCaloEventAction.s

# target to generate assembly for a file
MyCaloEventAction.cc.s:
	$(MAKE) -f CMakeFiles/MyCalo.dir/build.make CMakeFiles/MyCalo.dir/MyCaloEventAction.cc.s
.PHONY : MyCaloEventAction.cc.s

MyCaloHit.o: MyCaloHit.cc.o

.PHONY : MyCaloHit.o

# target to build an object file
MyCaloHit.cc.o:
	$(MAKE) -f CMakeFiles/MyCalo.dir/build.make CMakeFiles/MyCalo.dir/MyCaloHit.cc.o
.PHONY : MyCaloHit.cc.o

MyCaloHit.i: MyCaloHit.cc.i

.PHONY : MyCaloHit.i

# target to preprocess a source file
MyCaloHit.cc.i:
	$(MAKE) -f CMakeFiles/MyCalo.dir/build.make CMakeFiles/MyCalo.dir/MyCaloHit.cc.i
.PHONY : MyCaloHit.cc.i

MyCaloHit.s: MyCaloHit.cc.s

.PHONY : MyCaloHit.s

# target to generate assembly for a file
MyCaloHit.cc.s:
	$(MAKE) -f CMakeFiles/MyCalo.dir/build.make CMakeFiles/MyCalo.dir/MyCaloHit.cc.s
.PHONY : MyCaloHit.cc.s

MyCaloPrimaryGeneratorAction.o: MyCaloPrimaryGeneratorAction.cc.o

.PHONY : MyCaloPrimaryGeneratorAction.o

# target to build an object file
MyCaloPrimaryGeneratorAction.cc.o:
	$(MAKE) -f CMakeFiles/MyCalo.dir/build.make CMakeFiles/MyCalo.dir/MyCaloPrimaryGeneratorAction.cc.o
.PHONY : MyCaloPrimaryGeneratorAction.cc.o

MyCaloPrimaryGeneratorAction.i: MyCaloPrimaryGeneratorAction.cc.i

.PHONY : MyCaloPrimaryGeneratorAction.i

# target to preprocess a source file
MyCaloPrimaryGeneratorAction.cc.i:
	$(MAKE) -f CMakeFiles/MyCalo.dir/build.make CMakeFiles/MyCalo.dir/MyCaloPrimaryGeneratorAction.cc.i
.PHONY : MyCaloPrimaryGeneratorAction.cc.i

MyCaloPrimaryGeneratorAction.s: MyCaloPrimaryGeneratorAction.cc.s

.PHONY : MyCaloPrimaryGeneratorAction.s

# target to generate assembly for a file
MyCaloPrimaryGeneratorAction.cc.s:
	$(MAKE) -f CMakeFiles/MyCalo.dir/build.make CMakeFiles/MyCalo.dir/MyCaloPrimaryGeneratorAction.cc.s
.PHONY : MyCaloPrimaryGeneratorAction.cc.s

MyCaloRunAction.o: MyCaloRunAction.cc.o

.PHONY : MyCaloRunAction.o

# target to build an object file
MyCaloRunAction.cc.o:
	$(MAKE) -f CMakeFiles/MyCalo.dir/build.make CMakeFiles/MyCalo.dir/MyCaloRunAction.cc.o
.PHONY : MyCaloRunAction.cc.o

MyCaloRunAction.i: MyCaloRunAction.cc.i

.PHONY : MyCaloRunAction.i

# target to preprocess a source file
MyCaloRunAction.cc.i:
	$(MAKE) -f CMakeFiles/MyCalo.dir/build.make CMakeFiles/MyCalo.dir/MyCaloRunAction.cc.i
.PHONY : MyCaloRunAction.cc.i

MyCaloRunAction.s: MyCaloRunAction.cc.s

.PHONY : MyCaloRunAction.s

# target to generate assembly for a file
MyCaloRunAction.cc.s:
	$(MAKE) -f CMakeFiles/MyCalo.dir/build.make CMakeFiles/MyCalo.dir/MyCaloRunAction.cc.s
.PHONY : MyCaloRunAction.cc.s

MyCaloSD.o: MyCaloSD.cc.o

.PHONY : MyCaloSD.o

# target to build an object file
MyCaloSD.cc.o:
	$(MAKE) -f CMakeFiles/MyCalo.dir/build.make CMakeFiles/MyCalo.dir/MyCaloSD.cc.o
.PHONY : MyCaloSD.cc.o

MyCaloSD.i: MyCaloSD.cc.i

.PHONY : MyCaloSD.i

# target to preprocess a source file
MyCaloSD.cc.i:
	$(MAKE) -f CMakeFiles/MyCalo.dir/build.make CMakeFiles/MyCalo.dir/MyCaloSD.cc.i
.PHONY : MyCaloSD.cc.i

MyCaloSD.s: MyCaloSD.cc.s

.PHONY : MyCaloSD.s

# target to generate assembly for a file
MyCaloSD.cc.s:
	$(MAKE) -f CMakeFiles/MyCalo.dir/build.make CMakeFiles/MyCalo.dir/MyCaloSD.cc.s
.PHONY : MyCaloSD.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... MyCalo"
	@echo "... edit_cache"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... MyCalo.o"
	@echo "... MyCalo.i"
	@echo "... MyCalo.s"
	@echo "... MyCaloActionInitialization.o"
	@echo "... MyCaloActionInitialization.i"
	@echo "... MyCaloActionInitialization.s"
	@echo "... MyCaloDetectorConstruction.o"
	@echo "... MyCaloDetectorConstruction.i"
	@echo "... MyCaloDetectorConstruction.s"
	@echo "... MyCaloEventAction.o"
	@echo "... MyCaloEventAction.i"
	@echo "... MyCaloEventAction.s"
	@echo "... MyCaloHit.o"
	@echo "... MyCaloHit.i"
	@echo "... MyCaloHit.s"
	@echo "... MyCaloPrimaryGeneratorAction.o"
	@echo "... MyCaloPrimaryGeneratorAction.i"
	@echo "... MyCaloPrimaryGeneratorAction.s"
	@echo "... MyCaloRunAction.o"
	@echo "... MyCaloRunAction.i"
	@echo "... MyCaloRunAction.s"
	@echo "... MyCaloSD.o"
	@echo "... MyCaloSD.i"
	@echo "... MyCaloSD.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

